### ISSUE TITLE
[SearchInput] IE bug : la croix apparait dans le `input type="search"`

### ISSUE THREAD

**Issue by joachimesque** [KissKissBankBank/kitten#1526]
Sous IE11, la croix du `input type="search"` apparait. Il faut utiliser :

```css
input::-ms-clear {
  display: none;
}
```
