### ISSUE TITLE
[PlatformMenu] IE10, IE11 bug : flexbox

### ISSUE THREAD

**Issue by joachimesque** [KissKissBankBank/kitten#1531]
Peut-être lié à https://github.com/philipwalton/flexbugs/issues/128 ?

Ou alors c'est le deuxième élément (un svg avec un rotate) qui a des soucis de calcul de place ?

IE11
![image](https://user-images.githubusercontent.com/1781070/52116414-5a222f00-2611-11e9-920b-f9d02fe08371.png)

IE10
![image](https://user-images.githubusercontent.com/1781070/52116555-b84f1200-2611-11e9-89fa-a7313c59004b.png)

**Comment by joachimesque** [comment]
https://github.com/KissKissBankBank/kitten/blob/10ed3b198664773c0edb310c166380dd864bd4fb/assets/javascripts/kitten/components/menus/header-menu/components/item.js#L94

```css
  svg,
  img {
    max-height: ${pxToRem(24)};
    width: auto;
  }
```

C'est le `width: auto;` qui n'est pas bien digéré dans IE11 et qui donne une dimension étrange aux flèches. Ou bien on le supprime, ou bien on limite le scope CSS à :

```css
  svg:not(.k-ArrowIcon),
  img {
    max-height: ${pxToRem(24)};
    width: auto;
  }
```

pour que les règles ne s'apliquent qu'aux logos.
