### ISSUE TITLE
Map schemas

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#17]
Idée pour simplifier les schemas : créer un concept de types de maps nommées et validées.

Exemple :

``` scss
// application.scss
$typography-map: k-typography-definition(
  font-size: 1rem,
);

$border-button-map: k-border-definition(
  width: 1em,
);

$thin-button-map: k-border-definition(
  style: dotted,
);

$button-palette-map: k-color-palette-definition(
  active: (text: '#eee'),
  focus: (text: '#aaa'),
);


// …/definitions/_typography
function k-typography-definition($map) {
  // tout un tas de trucs ici qui
  // - vérifient que les valeurs requises sont présentes
  // - remplissent des valeurs par défaut
  raise "OHNOES" if { !font-size in $_map_ }
  return {
    font-size: $map['font-size'],
    font-weight: $map[:fontSize] || FAT
   }
}


// …/_button.scss
@mixin button(palette-map: $button-palette-map,
              border-map: $border-button-map,
              typography-map: $typography-map) {
  border: map-get($border-map, 'width') map-get($border-map, 'style');

  &:active {
    $active-color: map-get($button-palette-map, 'active');
    color: map-get($active-color, 'text'); 
  }
}
```
