### ISSUE TITLE
Proposition: `RichText` component

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#497]
Il peut s'avérer utile pour l'avenir de disposer d'un wrapper qui formate correctement du contenu.

Dans certains composants (`Alert`, `InformationBox`, etc.), nous injectons du texte dont nous ne maitrisons pas le contenu (liens, liste, etc.). Cela peut avoir l'effet où les composants (de manière isolée) doivent savoir à l'avance comment afficher tous les cas possibles. Ca va être assez redondant je pense à force.

Je vous propose de créer un composant générique pour gérer les différents styles de texte (`p, strong, ul, ol, li, blockquote, table, iframe, img, svg, etc.`).

Au niveau du nom, je propose `<RichText />` mais si vous avez mieux je suis preneur.

Ca donnerait un truc du style : 

```scss
// rich-text.scss

.k-RichText {
  p { … }
  ul, ol { … }
  iframe { … }
  table { … }
  … { … }
}

// Modifiers.

.k-RichText--center {
  text-align: center;
}

.k-RichText--tiny {
  font-size: 14px;
}
```

```js
// rich-text.js

import React from 'react'
import Markdown from 'react-markdown'

export class RichText extends React.Component {
  render() {
    return (
      <div className="k-RichText" { ...props }>
        { props.children }
      </div>
    )
  }
}

RichText.defaultProps = {
  tiny: false,
  center: false,
  …,
}
```

```js
// Usage:

import React from 'react'
import { Alert } from 'kitten/components/notifications/alert'
import { RichText } from 'kitten/components/typography/rich-text'

export const KarlAlert = props => {
  return (
    <Alert { ...props }>
      <RichText center>
        <Markdown renderers={ markdownRenderers }
          source="Lorem ipsum dolor sit amet, [consectetuer adipiscing](#) elit." />
      </RichText>
    </Alert>
  )
}
```

Qu'en pensez-vous ? (cc @camilledel, @Ynote, @sunny, @Morgan-jarry)
