### ISSUE TITLE
Feature: Color utilities

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#506]
On pourrait créer un utilitaire de gestion de la couleur pour pouvoir facilement ajouter une autre couleur dans un titre, paragraphe, etc. 

Exemple : 

```scss
.k-u-color-primary1 {
  color: map-get($k-colors, 'primary-1');
}

.k-u-color-primary2 {
  color: map-get($k-colors, 'primary-2');
}
```

Usage :

```html
<h1 class="k-Title">
  Ceci est un titre avec du texte en <span class="k-u-color-primary1">bleu</span>
</h1>
```

Exemple d'affichage : 

<img width="201" alt="capture d ecran 2017-03-08 a 16 01 31" src="https://cloud.githubusercontent.com/assets/736319/23709489/e8afb420-0419-11e7-9c0d-171744e2f769.png">
