### ISSUE TITLE
Mixin pour des animations

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#584]
Avec l'intégration de la page browsing de LENDO, ca pourrait être intéressant d'avoir un mixin pour gérer les animations (`FadeIn/FadeOut`, `SlideDown/SlideUp`, etc.). L'idée serait d'avoir pour chaque animation, une classe d'initialisation qu'on suffixerait par `--default` et une classe de lancement d'animation avec `--start`.

On pourrait avoir un truc dans ce style (sans mauvais jeu de mots :) : 

```css
@mixin k-Animation {
  .k-Animation__fadeIn--default {
    opacity: 0;
    visibility: hidden;
    transition: opacity .4s $easing, visibility .2s $easing;
  }

  .k-Animation__fadeIn--start {
    opacity: 1;
    visibility: visible;
  }

  .k-Animation__fadeOut--default {
    opacity: 1;
    visibility: visible;
    transition: opacity .4s $easing, visibility .2s $easing;
  }

  .k-Animation__fadeOut--start {
    opacity: 0;
    visibility: hidden;
  }
}
```

Ca vous semble bien ?

L'idée derrière cette proposition est d'également voir avec le produit pour créer des animations identiques pour les 3 plateformes avec les mêmes délais d'anim, etc.
