### ISSUE TITLE
Invoke all components inside Karl

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#87]
Suggestion de réorganisation pour que Karl invoque l'ensemble des composants, et que les applications puissent n'invoquer que ce dont elles ont besoin.
## Kitten

``` scss
// kitten/kitten.scss
@import "kitten/definitions/colors";

$k-colors: map-merge((
  primary: black,
  secondary: grey,
), $k-colors);
```

``` scss
// kitten/button.scss
@mixin k-Button($button) {
  $primary-background-color: k-color-definition(k-default(
    map-get($button, ('colors', 'primary-background')),
    map-get($k-colors, ('primary'))
  ));

  background-color: $primary-background-color;
}
```
## Karl

``` scss
// karl/karl.scss
@import "{CURRENT_APP}/app-config.scss";

@import "kitten";

@import "kitten/button";
@include k-Button;

@import "kitten/slider";
@include k-Slider;
```
## KissKissBankBank

``` scss
// kisskissbankbank/application.scss
@import "kisskissbankbank/app-config.scss";
@import "kitten";

@import "kitten/button";
@include k-Button;
@include k-with-prefix('kiss') {
  @include k-Button((colors: ( hover: salmon )));
}
```

``` scss
// kisskissbankbank/app-config.scss
$k-colors: k-merge($k-colors, (
  primary: blue
));
```
